job_research_task:
  description: >
    Analyze the job posting file provided: {job_description} to extract key skills, experiences, and qualifications required. Use the tools to gather content and identify and categorize the requirements
  expected_output: > 
    A structured list of job requirements, including necessary skills, qualifications and experiences
  agent: job_researcher

candidate_task:
  description: >
    Compile a detailed personal and professional profile using personal write-up. Utilize tools to extract  and synthesize information from these sources
  expected_output: >
    A comprehensive profile document that includes skiils, project experiences, interests and communication style
  agent: candidate_success

writer_task:
  description: >
    Analyze job descriptions to identify crucial keywords and industry trends, optimizing resumes to pass applicant tracking systems (ATS) while maintaining readability and engagement for hiring managers. Ensure consistency in formatting, clarity in technical descriptions, and a compelling narrative that differentiates candidates from the competition
  expected_output: >
    An updated resume that effectively highlights the candidate's  qualifications and experiences relevant to the job. The tome must be conversational and natural, replacing overly formal words with a more approachable style. The candidate is not native, the result must look genuine to this fact. Keep the resume short, not longer that 2 pages. I like having more details in the recent work experience and less in the rest
  agent: writer
  context: [job_research_task, candidate_task]

interview_task:
  description: >
    Develops key talking points aligned with the job and company culture. Helps structure my responses for clarity and impact. Guides you in anticipating and answering tricky questions. Coaches you on communication skills, confidence, and professional storytelling.
  expected_output: >
    A document containing key questions and talking  points that the candidate should prepare for the initial interview
  agent: interview_coach
  context: [job_research_task, candidate_task]

strategy_task:
  description: >
    Thoroughly review the candidate's resume and professional profile to gain a deep understanding of their background, strengths, and areas for development. Uncover candidate passions, motivations, and long-term vision, helping them define or refine their career objectives. evaluates job offers and opportunities to determine how well they align with the candidate's aspirations. They consider factors such as career progression, company culture, role responsibilities, and potential for skill development
  expected_output: >
    A job offer evaluation including criteria such as alignment with career goals, growth potential, company culture, compensation, and work-life balance.
  context: [job_research_task, candidate_task, writer_task]
  agent: strategist

industry_task:
  description: >
    Research developments, emerging technologies, regulatory changes, and market shifts to ensure advice is relevant and timely. Advise candidates on how to adjust their career approaches, resumes, and interview techniques to align with industry-specific trends and expectations
  expected_output: >
    A concise yet comprehensive guide designed to help the candidate navigate the specific position industry. It would serve as a practical, actionable roadmap for the candidate to succeed in the company industry. Advise on how to highlight relevant skills, experiences, and achievements in resumes. They may also provide insights into the language, terminology, and cultural norms of the industry, ensuring the candidate's communication aligns with what employers in that sector value.
  agent: industry
  context: [job_research_task, candidate_task]